export const AIOperationTypes = [
  "ADD-AI-ALERM",
  "SCRAPE-ALL-STOCK-TV",
  "SCRAPE-PRESET-TV",
  "SEND-PUSH-NOTIFICATION",
  "SEND-PUSH-NOTIFICATION-ANALYSIS",
  "SEND-PUSH-NOTIFICATION-TO-TRIAL-USER",
  "SEND-PUSH-NOTIFICATION-TO-FREE-USER",
  "SEND-PUSH-NOTIFICATION-COMMENT",
  "SEND-PUSH-NOTIFICATION-REACTION",
  "UPDATE-NEWS",
];
